#!/bin/bash
# -----------------------------------------------------------------------------
# Generates a btop .theme file from the active look's kitty palette (reusing
# the standard ANSI color roles every kitty look file already defines: red=1,
# green=2, yellow=3, blue=4, magenta=5, cyan=6) and points btop.conf at it.
#
# Called by toggle-look.sh as: apply-look.sh <look-name>
#
# btop reads its theme at process start, and this setup always spawns a
# fresh btop (CTRL+ALT+Delete -> kitty --class btop -e btop, per the float+
# pin window rule) rather than reusing a long-running instance, so there's
# no live-reload signal needed -- the next launch just picks up the change.
# -----------------------------------------------------------------------------
set -euo pipefail

look=${1:?usage: apply-look.sh <look-name>}
kitty_conf="$HOME/.config/kitty/looks/$look.conf"
themes_dir="$HOME/.config/btop/themes"
btop_conf="$HOME/.config/btop/btop.conf"
theme_file="$themes_dir/$look.theme"

if [ ! -f "$kitty_conf" ]; then
  echo "apply-look(btop): no kitty look file for '$look', leaving btop theme as-is" >&2
  exit 0
fi

field() { awk -v k="$1" '$1==k {print $2; exit}' "$kitty_conf"; }

bg=$(field background); fg=$(field foreground); cursor=$(field cursor)
dim=$(field color8)
red=$(field color1); red_b=$(field color9)
green=$(field color2); green_b=$(field color10)
yellow=$(field color3); yellow_b=$(field color11)
blue=$(field color4); blue_b=$(field color12)
magenta=$(field color5)
cyan=$(field color6)

mkdir -p "$themes_dir"
cat > "$theme_file" <<EOF
# Auto-generated by btop/apply-look.sh from kitty/looks/$look.conf -- edit
# that file (or this script's color-role mapping), not this one directly,
# it gets overwritten on every look toggle.

theme[main_bg]="$bg"
theme[main_fg]="$fg"
theme[title]="$fg"
theme[hi_fg]="$cursor"
theme[selected_bg]="$cursor"
theme[selected_fg]="$bg"
theme[inactive_fg]="$dim"
theme[graph_text]="$fg"
theme[meter_bg]="$dim"
theme[proc_misc]="$blue"

theme[cpu_box]="$red"
theme[mem_box]="$green"
theme[net_box]="$blue"
theme[proc_box]="$magenta"
theme[div_line]="$dim"

theme[temp_start]="$green"
theme[temp_mid]="$yellow"
theme[temp_end]="$red"

theme[cpu_start]="$green"
theme[cpu_mid]="$yellow"
theme[cpu_end]="$red"

theme[free_start]="$green"
theme[free_mid]="$green_b"
theme[free_end]="$green"

theme[cached_start]="$blue"
theme[cached_mid]="$blue_b"
theme[cached_end]="$blue"

theme[available_start]="$yellow"
theme[available_mid]="$yellow_b"
theme[available_end]="$yellow"

theme[used_start]="$red"
theme[used_mid]="$red_b"
theme[used_end]="$red"

theme[download_start]="$blue"
theme[download_mid]="$blue_b"
theme[download_end]="$cyan"

theme[upload_start]="$green"
theme[upload_mid]="$green_b"
theme[upload_end]="$cyan"

theme[process_start]="$green"
theme[process_mid]="$yellow"
theme[process_end]="$magenta"
EOF

if [ ! -f "$btop_conf" ]; then
  btop --default-config > "$btop_conf"
fi
sed -i "s/^color_theme = .*/color_theme = \"$look\"/" "$btop_conf"

# btop's own default is "cpu mem net proc" -- no GPU box. hyprland.lua's
# btop-float-pinned window rule is already sized assuming gpu0 is shown
# (see its own comment), so without this the window is oversized for
# what's actually in it and GPU load never shows without a manual toggle.
if ! grep -q '^shown_boxes = .*gpu0' "$btop_conf"; then
  sed -i 's/^shown_boxes = .*/shown_boxes = "cpu mem net proc gpu0"/' "$btop_conf"
fi
