#!/bin/bash
# -----------------------------------------------------------------------------
# Regenerates mako's colors.conf (included from the main mako config) from
# the active look's kitty palette -- same source of truth fuzzel/apply-look.sh
# and btop/apply-look.sh already use, instead of a third hand-maintained
# palette.
#
# Called by toggle-look.sh as: apply-look.sh <look-name>
#
# mako has a running daemon, so unlike fuzzel/btop this needs an explicit
# `makoctl reload` after -- toggle-look.sh does that, not this script.
# -----------------------------------------------------------------------------
set -euo pipefail

look=${1:?usage: apply-look.sh <look-name>}
kitty_conf="$HOME/.config/kitty/looks/$look.conf"
colors_conf="$HOME/.config/mako/colors.conf"

if [ ! -f "$kitty_conf" ]; then
  echo "apply-look(mako): no kitty look file for '$look', leaving mako colors as-is" >&2
  exit 0
fi

# mako wants #RRGGBB(AA); unlike fuzzel/btop's bare-hex format, keep the '#'.
field() { awk -v k="$1" '$1==k {print $2; exit}' "$kitty_conf"; }

bg=$(field background)
fg=$(field foreground)
cursor=$(field cursor)
dim=$(field color8)
red=$(field color1)

cat > "$colors_conf" <<EOF
# Auto-generated by mako/apply-look.sh from kitty/looks/$look.conf -- edit
# that file (or this script's color-role mapping), not this one directly,
# it gets overwritten on every look toggle.

background-color=${bg}E6
text-color=${fg}FF
border-color=${cursor}FF
progress-color=over ${dim}FF

[urgency=critical]
border-color=${red}FF
default-timeout=0
EOF
